#!/bin/bash

DATE=`date`
echo "$DATE: starting rip" >> /opt/rcp/var/log/restart

if [ -n "${RCPDBGDNS+x}" ]
then
	valgrind -v --leak-check=full --show-reachable=yes /opt/rcp/bin/rcpripd
else
	/opt/rcp/bin/rcpripd
fi
