#include "cmdparser.h"


int main() {
	int lineno = 0;
	char buf[MAX_LINE]; // input buffer

	printf("// this code was automatically generated by proccmds.awk\n");
	printf("#include \"librcp.h\"\n");
	printf("#include <sys/types.h>\n");
	printf("#include <sys/stat.h>\n");
	printf("#include <unistd.h>\n");
	printf("\n");
	printf("int module_initialize_commands(CliNode *head) {\n");
	printf("\tCliNode *node;\n");
	printf("\tCliMode mode = CLIMODE_ALL;\n");
	
	while (fgets(buf, MAX_LINE, stdin) != NULL) {
		lineno++;
		
		char *start = buf;
		while (*start == ' ' || *start == '\t' || *start == '\n')
			start++;

		// empty lines
		if (*start == '\0')
			continue;
		
		// comments
		if (*start == '#')
			continue;
		
		// more comments
		char *ptr = strchr(start, '#');
		if (ptr != NULL)
			*ptr = '\0';
		
		// strip end of string
		ptr = start + strlen(start);
		ptr--;
		while (*ptr == ' ' || *ptr == '\t' || *ptr == '\n')
			ptr--;
		ptr++;
		*ptr = '\0';
		
		// dispatch
		if (strncmp(start, "M:", 2) == 0)
			do_mode(start + 2, lineno);
		else if (strncmp(start, "C:", 2) == 0)
			do_command(start + 2, lineno);
		else if (strncmp(start, "Q:", 2) == 0)
			do_question(start + 2, lineno);
		else if (strncmp(start, "H:", 2) == 0)
			do_help(start + 2, lineno);
		else if (strncmp(start, "S:", 2) == 0)
			do_script(start + 2, lineno);
		else {
			printf("Error: invalid line %d - %s\n", lineno, start);
			return 1;
		}
	}

	printf("\n\treturn 0;\n");
	printf("}\n");
	
	return 0;
}
