#!/usr/bin/awk -f
BEGIN {
	FS = ":";
	printf("// this code was automatically generated by proccmds.awk\n");
	printf("#include \"librcp_cli.h\"\n");
	printf("\n");
	printf("int module_initialize_commands(CliNode *head) {\n");
	printf("\tCliNode *node;\n");
	printf("\tCliMode mode = CLIMODE_ALL;\n");
}
$1 == "#" {
	# do nothing, this is a comment
}

$1 == "C" {
	printf("\n\tif (cliParserAddCmd(mode, head, \"%s\")) return RCPERR;\n", $2);
	printf("\tif ((node = cliParserFindCmd(mode, head, \"%s\")) == NULL) return RCPERR;\n", $2);
}	

$1 == "H" {
	printf("\tif (cliParserAddHelp(head, \"%s\",  \"%s\")) return RCPERR;\n", $2, $3);
}

$1 == "M" {
	printf("\n\tmode = %s;\n", $2);
}

$1 == "F" {
	printf("\textern int %s(CliMode mode, int argc, char **argv);\n", $2);
	printf("\tif (cliAddFunction(node, %s)) return RCPERR;\n", $2);
}

END {
	printf("\n\treturn 0;\n");
	printf("}\n");
}