MAINLINE=../../..
EXECUTABLE=snmptrap
STATIC_LIBRARIES =  ../../system/net-snmp-5.7.1/snmplib/.libs/libnetsnmp.a
INCLUDE = -I../../system/net-snmp-5.7.1/include

include $(MAINLINE)/buildtools/common.mk
